[package]
name = "mist"
version = "0.7.0"
authors = ["LtPeriwinkle <not.yet.periwinkle@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.sdl2]
version = "0.34.3"
default-features = false
features = ["ttf"]

[dependencies.ron]
version = "0.6.2"

[dependencies.serde]
version = "1.0.60"
default-features = false
features = ["serde_derive"]
