[package]
name = "mist"
version = "0.2.0"
authors = ["LtPeriwinkle <not.yet.periwinkle@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(windows)'.dependencies.sdl2]
version = "^0.34.3"
default-features = false
features = ["ttf", "use-vcpkg"]

[target.'cfg(target_os = "linux")'.dependencies.sdl2]
version = "^0.34.3"
default-features = false
features = ["ttf", "bundled"]