name: build
on: pull_request

# create builds for mac and lin, windows requires a lot of setup so not doing that here
# don't compile with release or upload artifacts on PR
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsdl2-dev libsdl2-gfx-dev libsdl2-image-dev libsdl2-ttf-dev -y
      - name: Build
        run: cargo build
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          brew update
          brew install sdl2 sdl2_image sdl2_ttf sdl2_gfx
      - name: Build
        run: cargo build
